version: "3.8"

services:
  elasticsearch-alert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch-alert
    restart: always
    environment:
      - TZ=Asia/Shanghai
    # 挂载配置目录，容器内使用 /app/configs/config.yaml
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8080:8080"
