elasticsearch:
  addresses: ["http://localhost:9200"]
  username: ""
  password: ""
  tlsSkipVerify: false
  requestTimeout: "30s"
  provider: "opensearch" # 使用 OpenSearch 客户端，兼容旧版 Elasticsearch
  skipProductCheck: true

scheduler:
  timezone: "Asia/Shanghai"

rules:
  directory: "./configs/rules"
  sampleSize: 3
  defaultQuietPeriod: "10m"

notifications:
  webhook:
    url: ""
    headers: {}
    timeout: "5s"
  feishu:
    webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    enableAtAll: true
    timeout: "5s"
    titlePrefix: "[日志告警]"
    contentIntro: "检测到规则触发，以下为摘要与样例："
  dingtalk:
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    secret: "SECbd1123d0b434ac3dbd4f1f118f6148bafa3xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx""
    enableAtAll: true
    timeout: "5s"
  wechat:
    webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    timeout: "5s"
  email:
    host: "smtp.qq.com"
    port: 587
    username: "2099637909@qq.com"
    password: "xxxxxxxxxxxxxxxxx"
    from: "2099637909@qq.com"
    to: ["2099637909@qq.com"]
    useTLS: false
    tlsSkipVerify: false
    subjectPrefix: "[Log Alert]"
    timeout: "10s"
